/* eslint-disable @typescript-eslint/no-misused-promises */

import { type NextPage } from "next";
import Head from "next/head";
import { useRef, useState } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [link, setLink] = useState("");
  const linkRef = useRef<HTMLInputElement>(null);
  const { data, refetch, isLoading } = api.slideShare.query.useQuery({
    link,
  });

  const handleDownload = async () => {
    const value = linkRef?.current?.value;
    if (value) {
      setLink(value);
      await refetch();
    }

    console.log("run");
  };

  return (
    <>
      <Head>
        <title>Slideshare Downloader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Slideshare{" "}
            <span className="text-[hsl(280,100%,70%)]">Downloader</span>
          </h1>

          <div className="flex w-full max-w-lg flex-col gap-4 rounded-xl bg-white/10 p-4 text-white ">
            <h3 className="text-2xl font-bold">Embedded Link</h3>
            <form className="flex flex-col gap-2 md:gap-4">
              <input
                type="text"
                className="rounded px-4 py-2 text-black"
                defaultValue="https://www.slideshare.net/slideshow/embed_code/key/eqjDTzxthdlDus"
                ref={linkRef}
              />
              <button
                type="button"
                onClick={handleDownload}
                className="mx-auto rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
              >
                Download
              </button>
            </form>
          </div>
          <div className="text-2xl text-white">
            {isLoading ? "Downloading..." : <div>{data?.imgLinks}</div>}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
